services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-namenode
    environment:
      - CLUSTER_NAME=test
    ports:
      - 9000:9000
      - 9870:9870
    volumes:
      - namenode:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-datanode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    depends_on:
      - namenode
    volumes:
      - datanode:/hadoop/dfs/data
      
  hive-metastore:
    image: apache/hive:4.0.0
    container_name: hive-metastore
    environment:
      - SERVICE_NAME=metastore
      - DB_DRIVER=derby
      - HADOOP_HOME=/opt/hadoop
      - HIVE_METASTORE_HADOOP_OPTS=-Dfs.defaultFS=hdfs://namenode:9000
    ports:
      - 9083:9083
    depends_on:
      - namenode
    volumes:
      - hive-data:/opt/hive/data

# Define volumes section here
volumes:
  namenode:
  datanode:
  hive-data: